apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hugo-app
  name: hugo-app
  namespace: hugosite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hugo-app
  template:
    metadata:
      labels:
        app: hugo-app
    spec:
      containers:
        - name: hugo-app
          image: alfonsofortunato/hugo-app:master-0b72822e-1665785062 # {"$imagepolicy": "flux-system:hugoapp"}
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hugo-app
  name: hugo-app
  namespace: hugosite
spec:
  ports:
    - name: hugo-app
      port: 80
      targetPort: http
  selector:
    app: hugo-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"
    ingress.kubernetes.io/redirect-regex: "^https://(www.blogfolio.org|(blog.)?blogfolio.org)/?(.*)"
    ingress.kubernetes.io/redirect-replacement: "https://blogfolio.org/$3"
  name: hugo-app
  namespace: hugosite
spec:
  rules:
    - host: blogfolio.org
      http:
        paths:
          - backend:
              service:
                name: hugo-app
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: www.blogfolio.org
      http:
        paths:
          - backend:
              service:
                name: hugo-app
                port:
                  number: 80
            pathType: Prefix
            path: /
    - host: blog.blogfolio.org
      http:
        paths:
          - backend:
              service:
                name: hugo-app
                port:
                  number: 80
            pathType: Prefix
            path: /
  tls:
    - hosts:
        - blogfolio.org
        - www.blogfolio.org
        - blog.blogfolio.org
      secretName: blogfolio-tls
#     - hosts:
#         - portfolio.192.168.178.37.nip.io
