apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hugo-app
  name: hugo-app
  namespace: hugosite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hugo-app
  template:
    metadata:
      labels:
        app: hugo-app
    spec:s
      containers:
        - name: hugo-app
          image: alfonsofortunato/hugo-app:master-ebcb51c6-1625429662 # {"$imagepolicy": "flux-system:hugoapp"}
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hugo-app
  name: hugo-app
  namespace: hugosite
spec:
  ports:
    - name: 443
      port: 80
      targetPort: http
  selector:
    app: hugo-app
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: true
  name: hugo-app
  namespace: hugosite
spec:
  rules:
    - host: portfolio.192.168.178.37.nip.io
      http:
        paths:
          - backend:
              serviceName: hugo-app
              servicePort: 443
            path: /
  tls:
    - hosts:
        - portfolio.192.168.178.37.nip.io
