apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hugo-app
  name: hugo-app
  namespace: hugosite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hugo-app
  template:
    metadata:
      labels:
        app: hugo-app
    spec:
      containers:
        - name: hugo-app
          image: alfonsofortunato/hugo-app:master-fb8b8ca0-1625682784 # {"$imagepolicy": "flux-system:hugoapp"}
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hugo-app
  name: hugo-app
  namespace: hugosite
spec:
  ports:
    - name: hugo-app
      port: 80
      targetPort: http
  selector:
    app: hugo-app
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
  name: hugo-app
  namespace: hugosite
spec:
  rules:
    - host: moviemaker.ddnsfree.com
      http:
        paths:
          - backend:
              serviceName: hugo-app
              servicePort: 80
            path: /
  tls:
  - hosts:
    - moviemaker.ddnsfree.com
    secretName: moviemaker-tls
#     - hosts:
#         - portfolio.192.168.178.37.nip.io
