---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: hugoapp
  namespace: flux-system
spec:
  filterTags:
    pattern: '^master-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'  
  imageRepositoryRef:
    name: hugoapp
  policy:
    numerical:
      order: asc

