apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hugo-app
  name: hugo-app
  namespace: hugosite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hugo-app
  template:
    metadata:
      labels:
        app: hugo-app
    spec:
      containers:
        - name: hugo-app
          image: alfonsofortunato/hugo-app:master-bf91ee2c-1625427585 # {"$imagepolicy": "flux-system:hugoapp"}
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hugo-app
  name: hugo-app
  namespace: hugosite
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: hugo-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hugo-app
  namespace: hugosite
spec:
  rules:
    - host: portfolio.192.168.178.37.nip.io
      http:
        paths:
          - backend:
              serviceName: hugo-app
              servicePort: http
            path: /
  tls:
    - hosts:
        - portfolio.192.168.178.37.nip.io
